/**
 * Shared contract types for the Sudoku platform.
 * All teams import these definitions to ensure a single source of truth.
 */

/** Difficulty levels supported by the platform. */
export enum Difficulty {
  Easy = "easy",
  Medium = "medium",
  Hard = "hard",
}

/** A single cell value. 0 represents an empty cell. */
export type Cell = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9;

/** A 9×9 Sudoku board. The type does not enforce length at compile time, but all implementations must provide a 9×9 array of Cell. */
export type Board = Cell[][];

/** Core domain entity representing a puzzle. */
export interface Puzzle {
  /** The current board state; 0 indicates an empty cell. */
  board: Board;
  /** Difficulty of the puzzle. */
  difficulty: Difficulty;
}

/** Request shape for fetching a new puzzle. */
export interface PuzzleRequest {
  /** Desired difficulty level. */
  difficulty: Difficulty;
}

/** Response shape for a puzzle request. */
export interface PuzzleResponse {
  /** The generated board. */
  board: Board;
  /** The difficulty of the generated puzzle. */
  difficulty: Difficulty;
}

/** Request shape for validating a completed board. */
export interface ValidateRequest {
  /** The board to validate. */
  board: Board;
}

/** Response shape for board validation. */
export interface ValidateResponse {
  /** True when the board satisfies Sudoku rules. */
  valid: boolean;
}

/** Core domain entity representing a score entry. */
export interface Score {
  /** Unique identifier generated by the Scores service. */
  id: string;
  /** Player's display name. */
  playerName: string;
  /** Difficulty of the puzzle that was solved. */
  difficulty: Difficulty;
  /** Time taken to solve the puzzle, in seconds. Must be a non‑negative number. */
  timeToSolve: number;
}

/** Request shape for persisting a completed game result. */
export interface ScoreRequest {
  /** Player's display name – must be a non‑empty string. */
  playerName: string;
  /** Difficulty of the puzzle that was solved. */
  difficulty: Difficulty;
  /** Time taken to solve the puzzle, in seconds – must be greater than zero. */
  timeToSolve: number;
}

/** Response shape after storing a score. */
export interface ScoreResponse {
  /** Identifier of the newly created score record. */
  id: string;
}

/** Single entry in a leaderboard. */
export interface LeaderboardEntry {
  /** Player's display name. */
  playerName: string;
  /** Time taken to solve the puzzle, in seconds. */
  timeToSolve: number;
}

/** Request shape for retrieving a leaderboard. */
export interface LeaderboardRequest {
  /** Difficulty for which the leaderboard is requested. */
  difficulty: Difficulty;
}

/** Response shape containing the top entries for a difficulty. */
export interface LeaderboardResponse {
  /** Ordered list of leaderboard entries (best times first). */
  entries: LeaderboardEntry[];
}
